DROP TABLE IF EXISTS Cards;

CREATE TABLE Cards (
  id INT NOT NULL AUTO_INCREMENT,
  value INT NOT NULL,
  face VARCHAR(5) NOT NULL,
  suit VARCHAR(8) NOT NULL,
  imgSrc VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO Cards (value, face, suit, imgSrc) VALUES
  (0, 'Ace', 'Spades', 'images/AceOfSpades.jpg'),
  (0, 'Ace', 'Hearts', 'images/AceOfHearts.jpg'),
  (0, 'Ace', 'Diamonds', 'images/AceOfDiamonds.jpg'),
  (0, 'Ace', 'Clubs', 'images/AceOfClubs.jpg'),
  (1, 'Two', 'Spades', 'images/TwoOfSpades.jpg'),
  (1, 'Two', 'Hearts', 'images/TwoOfHearts.jpg'),
  (1, 'Two', 'Diamonds', 'images/TwoOfDiamonds.jpg'),
  (1, 'Two', 'Clubs', 'images/TwoOfClubs.jpg'),
  (2, 'Three', 'Spades', 'images/ThreeOfSpades.jpg'),
  (2, 'Three', 'Hearts', 'images/ThreeOfHearts.jpg'),
  (2, 'Three', 'Diamonds', 'images/ThreeOfDiamonds.jpg'),
  (2, 'Three', 'Clubs', 'images/ThreeOfClubs.jpg'),
  (3, 'Four', 'Spades', 'images/FourOfSpades.jpg'),
  (3, 'Four', 'Hearts', 'images/FourOfHearts.jpg'),
  (3, 'Four', 'Diamonds', 'images/FourOfDiamonds.jpg'),
  (3, 'Four', 'Clubs', 'images/FourOfClubs.jpg'),
  (4, 'Five', 'Spades', 'images/FiveOfSpades.jpg'),
  (4, 'Five', 'Hearts', 'images/FiveOfHearts.jpg'),
  (4, 'Five', 'Diamonds', 'images/FiveOfDiamonds.jpg'),
  (4, 'Five', 'Clubs', 'images/FiveOfClubs.jpg'),
  (5, 'Six', 'Spades', 'images/SixOfSpades.jpg'),
  (5, 'Six', 'Hearts', 'images/SixOfHearts.jpg'),
  (5, 'Six', 'Diamonds', 'images/SixOfDiamonds.jpg'),
  (5, 'Six', 'Clubs', 'images/SixOfClubs.jpg'),
  (6, 'Seven', 'Spades', 'images/SevenOfSpades.jpg'),
  (6, 'Seven', 'Hearts', 'images/SevenOfHearts.jpg'),
  (6, 'Seven', 'Diamonds', 'images/SevenOfDiamonds.jpg'),
  (6, 'Seven', 'Clubs', 'images/SevenOfClubs.jpg'),
  (7, 'Eight', 'Spades', 'images/EightOfSpades.jpg'),
  (7, 'Eight', 'Hearts', 'images/EightOfHearts.jpg'),
  (7, 'Eight', 'Diamonds', 'images/EightOfDiamonds.jpg'),
  (7, 'Eight', 'Clubs', 'images/EightOfClubs.jpg'),
  (8, 'Nine', 'Spades', 'images/NineOfSpades.jpg'),
  (8, 'Nine', 'Hearts', 'images/NineOfHearts.jpg'),
  (8, 'Nine', 'Diamonds', 'images/NineOfDiamonds.jpg'),
  (8, 'Nine', 'Clubs', 'images/NineOfClubs.jpg'),
  (9, 'Ten', 'Spades', 'images/TenOfSpades.jpg'),
  (9, 'Ten', 'Hearts', 'images/TenOfHearts.jpg'),
  (9, 'Ten', 'Diamonds', 'images/TenOfDiamonds.jpg'),
  (9, 'Ten', 'Clubs', 'images/TenOfClubs.jpg'),
  (10, 'Jack', 'Spades', 'images/JackOfSpades.jpg'),
  (10, 'Jack', 'Hearts', 'images/JackOfHearts.jpg'),
  (10, 'Jack', 'Diamonds', 'images/JackOfDiamonds.jpg'),
  (10, 'Jack', 'Clubs', 'images/JackOfClubs.jpg'),
  (11, 'Queen', 'Spades', 'images/QueenOfSpades.jpg'),
  (11, 'Queen', 'Hearts', 'images/QueenOfHearts.jpg'),
  (11, 'Queen', 'Diamonds', 'images/QueenOfDiamonds.jpg'),
  (11, 'Queen', 'Clubs', 'images/QueenOfClubs.jpg'),
  (12, 'King', 'Spades', 'images/KingOfSpades.jpg'),
  (12, 'King', 'Hearts', 'images/KingOfHearts.jpg'),
  (12, 'King', 'Diamonds', 'images/KingOfDiamonds.jpg'),
  (12, 'King', 'Clubs', 'images/KingOfClubs.jpg');
